# Generated by Django 5.0.7 on 2024-08-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.TextField(max_length=255)),
                ('senha', models.TextField()),
            ],
        ),
    ]
